// app.vue
<template>
  <div class="min-h-screen bg-background">
    <!-- Header -->
    <DashboardHeader 
      @toggle-filters="showFilters = !showFilters"
      @export="handleExport"
    />

    <div class="container mx-auto px-6 py-6">
      <!-- Filter Panel -->
      <div v-if="showFilters" class="mb-6">
        <FilterPanel 
          v-model:search-query="dashboardStore.filters.searchQuery"
          v-model:selected-product="dashboardStore.filters.selectedProduct"
          v-model:date-range="dashboardStore.filters.dateRange"
          :products="products"
          @reset="dashboardStore.resetFilters"
        />
        <div class="border-t my-6"></div>
      </div>

      <!-- KPI Cards -->
      <div class="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-4 gap-6 mb-6">
        <KPICard
          title="Total Products"
          :value="dashboardStore.stats.totalProducts"
          subtitle="+12% from last month"
          :icon="Package"
          @click="activeTab = 'products'"
        />
        <KPICard
          title="Total Comments"
          :value="dashboardStore.stats.totalComments"
          subtitle="+23% from last month"
          :icon="MessageSquare"
          @click="activeTab = 'comments'"
        />
        <KPICard
          title="Unique Keywords"
          :value="dashboardStore.stats.uniqueKeywords"
          subtitle="+5% from last month"
          :icon="Tag"
        />
        <KPICard
          title="Sales Changes"
          :value="dashboardStore.stats.productsWithSalesChanges"
          subtitle="Products with changes"
          :icon="TrendingUp"
          @click="activeTab = 'sales'"
        />
      </div>

      <!-- Main Content -->
      <div class="space-y-6">
        <!-- Tab Navigation -->
        <div class="flex space-x-1 bg-muted p-1 rounded-lg">
          <button
            v-for="tab in tabs"
            :key="tab.value"
            @click="activeTab = tab.value"
            :class="[
              'flex-1 px-3 py-2 text-sm font-medium rounded-md transition-colors',
              activeTab === tab.value
                ? 'bg-background text-foreground shadow-sm'
                : 'text-muted-foreground hover:text-foreground'
            ]"
          >
            {{ tab.label }}
          </button>
        </div>

        <!-- Tab Content -->
        <div class="space-y-6">
          <!-- Overview Tab -->
          <div v-if="activeTab === 'overview'" class="space-y-6">
            <AnalysisPanel />
          </div>

          <!-- Products Tab -->
          <div v-if="activeTab === 'products'">
            <ProductTable 
              :search-query="dashboardStore.filters.searchQuery"
              :selected-product="dashboardStore.filters.selectedProduct"
            />
          </div>

          <!-- Comments Tab -->
          <div v-if="activeTab === 'comments'">
            <CommentTable 
              :search-query="dashboardStore.filters.searchQuery"
              :selected-product="dashboardStore.filters.selectedProduct"
            />
          </div>

          <!-- Sales Tab -->
          <div v-if="activeTab === 'sales'">
            <SalesTable 
              :search-query="dashboardStore.filters.searchQuery"
              :selected-product="dashboardStore.filters.selectedProduct"
            />
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted } from 'vue';
import { Package, MessageSquare, Tag, TrendingUp } from 'lucide-vue-next';
import { useDashboardStore } from '~/stores/dashboard';

// Store
const dashboardStore = useDashboardStore();

// Local state
const activeTab = ref('overview');
const showFilters = ref(false);
const products = ref([]);

// Tab configuration
const tabs = [
  { value: 'overview', label: 'Overview' },
  { value: 'products', label: 'Products' },
  { value: 'comments', label: 'Comments' },
  { value: 'sales', label: 'Sales Snapshots' }
];

// Methods
const handleExport = () => {
  // TODO: Implement export functionality
  console.log('Export clicked');
};

// Load initial data
onMounted(async () => {
  await dashboardStore.fetchStats();
  
  // Load products for filter dropdown
  try {
    const { data } = await $fetch('/api/products/index');
    products.value = data.products || [];
  } catch (error) {
    console.error('Failed to load products:', error);
  }
});
</script>

// FIGMA-UI/App.tsx
import React, { useState } from 'react';
import { Card, CardContent, CardHeader, CardTitle } from './components/ui/card';
import { Tabs, TabsContent, TabsList, TabsTrigger } from './components/ui/tabs';
import { Button } from './components/ui/button';
import { Input } from './components/ui/input';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from './components/ui/select';
import { Badge } from './components/ui/badge';
import { Separator } from './components/ui/separator';
import { ProductTable } from './components/ProductTable';
import { CommentTable } from './components/CommentTable';
import { SalesTable } from './components/SalesTable';
import { AnalysisPanel } from './components/AnalysisPanel';
import { FilterPanel } from './components/FilterPanel';
import { 
  Package, 
  MessageSquare, 
  Tag, 
  TrendingUp,
  Search,
  Download,
  Filter
} from 'lucide-react';

// Mock data for KPIs
const mockKPIs = {
  totalProducts: 1247,
  totalComments: 8934,
  uniqueKeywords: 342,
  productsWithSalesChanges: 89
};

export default function App() {
  const [activeTab, setActiveTab] = useState('overview');
  const [searchQuery, setSearchQuery] = useState('');
  const [selectedProduct, setSelectedProduct] = useState('all');
  const [showFilters, setShowFilters] = useState(false);

  return (
    <div className="min-h-screen bg-background">
      {/* Header */}
      <div className="border-b bg-card">
        <div className="container mx-auto px-6 py-4">
          <div className="flex items-center justify-between">
            <div>
              <h1>Sales & Comment Analytics Dashboard</h1>
              <p className="text-muted-foreground">
                Analyze product performance and customer feedback trends
              </p>
            </div>
            <div className="flex items-center gap-2">
              <Button variant="outline" size="sm" onClick={() => setShowFilters(!showFilters)}>
                <Filter className="h-4 w-4 mr-2" />
                Filters
              </Button>
              <Button variant="outline" size="sm">
                <Download className="h-4 w-4 mr-2" />
                Export
              </Button>
            </div>
          </div>
        </div>
      </div>

      <div className="container mx-auto px-6 py-6">
        {/* Filter Panel */}
        {showFilters && (
          <>
            <FilterPanel 
              searchQuery={searchQuery}
              setSearchQuery={setSearchQuery}
              selectedProduct={selectedProduct}
              setSelectedProduct={setSelectedProduct}
            />
            <Separator className="my-6" />
          </>
        )}

        {/* KPI Cards */}
        <div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-4 gap-6 mb-6">
          <Card className="cursor-pointer hover:shadow-md transition-shadow" onClick={() => setActiveTab('products')}>
            <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
              <CardTitle className="text-sm">Total Products</CardTitle>
              <Package className="h-4 w-4 text-muted-foreground" />
            </CardHeader>
            <CardContent>
              <div className="text-2xl">{mockKPIs.totalProducts.toLocaleString()}</div>
              <p className="text-xs text-muted-foreground">
                +12% from last month
              </p>
            </CardContent>
          </Card>

          <Card className="cursor-pointer hover:shadow-md transition-shadow" onClick={() => setActiveTab('comments')}>
            <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
              <CardTitle className="text-sm">Total Comments</CardTitle>
              <MessageSquare className="h-4 w-4 text-muted-foreground" />
            </CardHeader>
            <CardContent>
              <div className="text-2xl">{mockKPIs.totalComments.toLocaleString()}</div>
              <p className="text-xs text-muted-foreground">
                +23% from last month
              </p>
            </CardContent>
          </Card>

          <Card className="cursor-pointer hover:shadow-md transition-shadow">
            <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
              <CardTitle className="text-sm">Unique Keywords</CardTitle>
              <Tag className="h-4 w-4 text-muted-foreground" />
            </CardHeader>
            <CardContent>
              <div className="text-2xl">{mockKPIs.uniqueKeywords}</div>
              <p className="text-xs text-muted-foreground">
                +5% from last month
              </p>
            </CardContent>
          </Card>

          <Card className="cursor-pointer hover:shadow-md transition-shadow" onClick={() => setActiveTab('sales')}>
            <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
              <CardTitle className="text-sm">Sales Changes</CardTitle>
              <TrendingUp className="h-4 w-4 text-muted-foreground" />
            </CardHeader>
            <CardContent>
              <div className="text-2xl">{mockKPIs.productsWithSalesChanges}</div>
              <p className="text-xs text-muted-foreground">
                Products with changes
              </p>
            </CardContent>
          </Card>
        </div>

        {/* Main Content */}
        <Tabs value={activeTab} onValueChange={setActiveTab} className="space-y-6">
          <TabsList className="grid w-full grid-cols-4">
            <TabsTrigger value="overview">Overview</TabsTrigger>
            <TabsTrigger value="products">Products</TabsTrigger>
            <TabsTrigger value="comments">Comments</TabsTrigger>
            <TabsTrigger value="sales">Sales Snapshots</TabsTrigger>
          </TabsList>

          <TabsContent value="overview" className="space-y-6">
            <AnalysisPanel />
          </TabsContent>

          <TabsContent value="products">
            <ProductTable searchQuery={searchQuery} selectedProduct={selectedProduct} />
          </TabsContent>

          <TabsContent value="comments">
            <CommentTable searchQuery={searchQuery} selectedProduct={selectedProduct} />
          </TabsContent>

          <TabsContent value="sales">
            <SalesTable searchQuery={searchQuery} selectedProduct={selectedProduct} />
          </TabsContent>
        </Tabs>
      </div>
    </div>
  );
}
