// FIGMA-UI-Analysis/src/components/FilterPanel.tsx
import React from 'react';
import { Card, CardContent, CardHeader, CardTitle } from './ui/card';
import { Input } from './ui/input';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from './ui/select';
import { Button } from './ui/button';
import { Search, RotateCcw } from 'lucide-react';

interface FilterPanelProps {
  searchQuery: string;
  setSearchQuery: (query: string) => void;
  selectedProduct: string;
  setSelectedProduct: (product: string) => void;
}

// Mock product list
const mockProducts = [
  { id: '1', name: 'Wireless Headphones Pro' },
  { id: '2', name: 'Smart Fitness Tracker' },
  { id: '3', name: 'Gaming Keyboard RGB' },
  { id: '4', name: 'USB-C Hub 7-in-1' },
  { id: '5', name: 'Portable Phone Stand' }
];

export function FilterPanel({ 
  searchQuery, 
  setSearchQuery, 
  selectedProduct, 
  setSelectedProduct 
}: FilterPanelProps) {
  const handleReset = () => {
    setSearchQuery('');
    setSelectedProduct('all');
  };

  return (
    <Card>
      <CardHeader>
        <CardTitle>Filters & Controls</CardTitle>
      </CardHeader>
      <CardContent>
        <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
          {/* Search */}
          <div className="space-y-2">
            <label>Search</label>
            <div className="relative">
              <Search className="absolute left-3 top-1/2 transform -translate-y-1/2 h-4 w-4 text-muted-foreground" />
              <Input
                placeholder="Search products, comments..."
                value={searchQuery}
                onChange={(e) => setSearchQuery(e.target.value)}
                className="pl-10"
              />
            </div>
          </div>

          {/* Product Selector */}
          <div className="space-y-2">
            <label>Product</label>
            <Select value={selectedProduct} onValueChange={setSelectedProduct}>
              <SelectTrigger>
                <SelectValue placeholder="All products" />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="all">All products</SelectItem>
                {mockProducts.map((product) => (
                  <SelectItem key={product.id} value={product.id}>
                    {product.name}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
          </div>

          {/* Date Range */}
          <div className="space-y-2">
            <label>Date Range</label>
            <Select defaultValue="30days">
              <SelectTrigger>
                <SelectValue />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="7days">Last 7 days</SelectItem>
                <SelectItem value="30days">Last 30 days</SelectItem>
                <SelectItem value="90days">Last 90 days</SelectItem>
                <SelectItem value="1year">Last year</SelectItem>
              </SelectContent>
            </Select>
          </div>

          {/* Reset Button */}
          <div className="space-y-2">
            <label className="invisible">Reset</label>
            <Button variant="outline" onClick={handleReset} className="w-full">
              <RotateCcw className="h-4 w-4 mr-2" />
              Reset
            </Button>
          </div>
        </div>
      </CardContent>
    </Card>
  );
}

// components/FilterPanel.vue
<template>
  <Card>
    <div class="p-6">
      <h3 class="text-lg font-semibold mb-4">Filters & Controls</h3>
      <div class="grid grid-cols-1 md:grid-cols-4 gap-4">
        <!-- Search -->
        <div class="space-y-2">
          <label class="text-sm font-medium">Search</label>
          <div class="relative">
            <Search class="absolute left-3 top-1/2 transform -translate-y-1/2 h-4 w-4 text-muted-foreground" />
            <Input
              v-model="localSearchQuery"
              placeholder="Search products, comments..."
              class="pl-10"
            />
          </div>
        </div>

        <!-- Product Selector -->
        <div class="space-y-2">
          <label class="text-sm font-medium">Product</label>
          <select 
            v-model="localSelectedProduct"
            class="flex h-10 w-full rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2"
          >
            <option value="all">All products</option>
            <option v-for="product in products" :key="product.id" :value="product.id">
              {{ product.name }}
            </option>
          </select>
        </div>

        <!-- Date Range -->
        <div class="space-y-2">
          <label class="text-sm font-medium">Date Range</label>
          <select 
            v-model="localDateRange"
            class="flex h-10 w-full rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2"
          >
            <option value="7days">Last 7 days</option>
            <option value="30days">Last 30 days</option>
            <option value="90days">Last 90 days</option>
            <option value="1year">Last year</option>
          </select>
        </div>

        <!-- Reset Button -->
        <div class="space-y-2">
          <label class="text-sm font-medium invisible">Reset</label>
          <Button variant="outline" @click="handleReset" class="w-full">
            <RotateCcw class="h-4 w-4 mr-2" />
            Reset
          </Button>
        </div>
      </div>
    </div>
  </Card>
</template>

<script setup lang="ts">
import { Search, RotateCcw } from 'lucide-vue-next';
import { ref, watch } from 'vue';

interface Product {
  id: string;
  name: string;
}

interface Props {
  searchQuery: string;
  selectedProduct: string;
  dateRange: string;
  products: Product[];
}

const props = defineProps<Props>();

const emit = defineEmits<{
  'update:searchQuery': [value: string];
  'update:selectedProduct': [value: string];
  'update:dateRange': [value: string];
  reset: [];
}>();

const localSearchQuery = ref(props.searchQuery);
const localSelectedProduct = ref(props.selectedProduct);
const localDateRange = ref(props.dateRange);

watch(localSearchQuery, (newValue) => {
  emit('update:searchQuery', newValue);
});

watch(localSelectedProduct, (newValue) => {
  emit('update:selectedProduct', newValue);
});

watch(localDateRange, (newValue) => {
  emit('update:dateRange', newValue);
});

const handleReset = () => {
  localSearchQuery.value = '';
  localSelectedProduct.value = 'all';
  localDateRange.value = '30days';
  emit('reset');
};
</script>
